insert into ingredients values(401,'cake flour');
insert into ingredients values(402,'baking powder');
insert into ingredients values(403,'salt');
insert into ingredients values(404,'unsalted butter');
insert into ingredients values(405,'sugar');
insert into ingredients values(406,'large eggs, at room temperature');
insert into ingredients values(407,' buttermilk, at room temperature');
insert into ingredients values(408,'vanilla extract');

insert into ingredients values(409,'graham cracker crumbs');
insert into ingredients values(410,'packed light brown sugar');
insert into ingredients values(411,'of kosher salt');
insert into ingredients values(412,'unsalted butter, melted');
insert into ingredients values(413,'large egg yolks');
insert into ingredients values(414,'sweetened condensed milk');
insert into ingredients values(415,'fresh Key lime juice');
insert into ingredients values(416,'Unsweetened whipped cream');
insert into ingredients values(417,'Key lime slices');

insert into ingredients values(418,'yellow cake mix');
insert into ingredients values(419,'butter softened Tasty tip');
insert into ingredients values(420,'eggs');
insert into ingredients values(421,'sprinkles divided into two 1/3 cups');
insert into ingredients values(422,'sweetened condensed milk');
insert into ingredients values(423,'white chocolate chips');

insert into ingredients values(424,'sugar');
insert into ingredients values(425,'butter one 4 oz. stick Tasty tip');
insert into ingredients values(426,'eggs');
insert into ingredients values(427,'bananas medium ripe, smashed');
insert into ingredients values(428,'imitation vanilla extract ');
insert into ingredients values(429,'white flour all-purpose');
insert into ingredients values(430,'cup chopped walnuts');
insert into ingredients values(431,'baking soda');
insert into ingredients values(432,'salt');
insert into ingredients values(433,'ground cinnamon');

insert into ingredients values(434,'all-purpose flour');
insert into ingredients values(435,'salt');
insert into ingredients values(436,'instant yeast');
insert into ingredients values(437,'milk');
insert into ingredients values(438,'greek style plain yogurt');
insert into ingredients values(439,'sugar');
insert into ingredients values(440,'ground cardamom');
insert into ingredients values(441,'ground turmeric');
insert into ingredients values(442,'ghee melted, or butter');

insert into ingredients values(443,'grapeseed oil organic');
insert into ingredients values(444,'chopped fresh sage  finely ');
insert into ingredients values(445,'butternut squash  peeled, seeded, and cut into small  pieces ');
insert into ingredients values(446,'yellow onion  medium, chopped ');
insert into ingredients values(447,'garlic cloves pressed and minced ');
insert into ingredients values(448,'red pepper flakes  optional ');
insert into ingredients values(449,'low sodium vegetable broth');
insert into ingredients values(450,'gluten  free linguine');
insert into ingredients values(451,'cup raw cashews');
insert into ingredients values(452,'cups water');
insert into ingredients values(453,'lemon juice');
insert into ingredients values(454,'Himalayan salt pink, and additional to taste');
insert into ingredients values(455,'ground black pepper Freshly');

insert into ingredients values(456,'boneless skinless chicken breasts (cut into 1-inch chunks)');
insert into ingredients values(457,'large eggs (beaten)');
insert into ingredients values(458,'panko breadcrumbs');
insert into ingredients values(459,'honey');
insert into ingredients values(460,'soy sauce');
insert into ingredients values(461,'Sriracha');
insert into ingredients values(462,'garlic powder');
insert into ingredients values(463,'warm water');
insert into ingredients values(464,'corn starch');
insert into ingredients values(465,'green onions (thinly sliced)');
insert into ingredients values(466,'sesame seeds');

insert into ingredients values(467,'tofu (frozen and pressed)');
insert into ingredients values(468,'corn starch');
insert into ingredients values(469,'coconut oil (or vegetable oil of your choice)');
insert into ingredients values(470,'soy sauce (or tamari)');
insert into ingredients values(471,'Sriracha (or hot sauce of your choice)');
insert into ingredients values(472,'maple syrup');
insert into ingredients values(473,'rice vinegar');

insert into ingredients values(474,'shredded jack cheese (divided)');
insert into ingredients values(475,'fat-free sour cream');
insert into ingredients values(476,'(1 ounce) grated fresh Parmesan cheese, divided');
insert into ingredients values(477,'garlic (minced)');
insert into ingredients values(478,'artichoke hearts (canned or frozen and thawed)');
insert into ingredients values(479,'fat-free cream cheese, softened');
insert into ingredients values(480,'frozen chopped spinach, thawed, drained, and squeezed dry');

insert into ingredients values(481,'large baking potatoes, peeled, rinsed, and sliced into french fry shaped pieces');
insert into ingredients values(482,'vegetable oil, for tossing');
insert into ingredients values(483,'Salt and pepper');
insert into ingredients values(484,'parsley, chopped fresh');

insert into ingredients values(485,'red potatoes, peeled');
insert into ingredients values(486,'garlic cloves, smashed');
insert into ingredients values(487,'kosher salt');
insert into ingredients values(488,'bacon, rendered crisp');
insert into ingredients values(489,'rendered bacon fat');
insert into ingredients values(490,'head green cabbage, cored and thinly shredded');
insert into ingredients values(491,'kale, chopped');
insert into ingredients values(492,'milk');
insert into ingredients values(493,'heavy cream');
insert into ingredients values(494,'freshly cracked black pepperkosher salt to taste');
insert into ingredients values(495,'unsalted butter');
insert into ingredients values(496,'chives, chopped fine');

insert into ingredients values(497,'cooking spray');
insert into ingredients values(498,'reduced fat cream cheese, softened');
insert into ingredients values(499,'reduced fat sour cream');
insert into ingredients values(500,'Franks hot sauce (or whatever hot sauce you like)');
insert into ingredients values(501,'white wine vinegar');
insert into ingredients values(502,'cooked peeled large shrimp, diced');
insert into ingredients values(503,'reduced fat Sargento Mexican blend');

insert into ingredients values(504,'chicken wing pieces one wing makes 2 pieces, the flat and the drum');
insert into ingredients values(505,'vegetable oil');
insert into ingredients values(506,'salt');
insert into ingredients values(507,'all-purpose flour');
insert into ingredients values(508,'white vinegar');
insert into ingredients values(509,'cayenne pepper');
insert into ingredients values(510,'garlic powder');
insert into ingredients values(511,'Worcestershire sauce');
insert into ingredients values(512,'Tabasco sauce');
insert into ingredients values(513,'salt');
insert into ingredients values(514,'Louisiana hot sauce Franks is the brand used in Buffalo');
insert into ingredients values(515,'unsalted butter or margarine');
insert into ingredients values(516,'celery sticks');
insert into ingredients values(517,'blue cheese dressing');

insert into ingredients values(518,'pineapple juice');
insert into ingredients values(519,'CRYSTAL LIGHT Classic Orange Flavor Drink Mix');
insert into ingredients values(520,'club soda');
insert into ingredients values(521,'navel orange, cut into 10 thin slices');

insert into ingredients values(522,'Raspberry Ice Flavor Drink Mix');
insert into ingredients values(523,'low-calorie cranberry juice cocktail');
insert into ingredients values(524,'orange juice');
insert into ingredients values(525,'white grape juice');
insert into ingredients values(526,'club soda');

insert into ingredients values(527,'whole-wheat spaghetti');
insert into ingredients values(528,'reduced-sodium soy sauce');
insert into ingredients values(529,'sesame oil');
insert into ingredients values(530,'canola oil');
insert into ingredients values(531,'rice-wine vinegar, or lime juice');
insert into ingredients values(532,'crushed red pepper');
insert into ingredients values(533,'scallions, sliced, divided');
insert into ingredients values(534,'chopped fresh cilantro, divided optional');
insert into ingredients values(535,'snow peas, trimmed and sliced on the bias');
insert into ingredients values(536,'red bell pepper, thinly sliced');
insert into ingredients values(537,'toasted sesame seeds');

insert into ingredients values(538,'garbanzo or garbanzo beans');
insert into ingredients values(539,'onions small, roughly chopped');
insert into ingredients values(540,'fresh parsley chopped');
insert into ingredients values(541,'garlic I prefer roasted');
insert into ingredients values(542,'flour');
insert into ingredients values(543,'salt');
insert into ingredients values(544,'cumin');
insert into ingredients values(545,'ground coriander');
insert into ingredients values(546,'black pepper');
insert into ingredients values(547,'cayenne pepper');
insert into ingredients values(548,'ground cardamom');
insert into ingredients values(549,'vegetable oil for frying, grapeseed, canola, and peanut oil work well');

insert into ingredients values(550,'extra virgin olive oil');
insert into ingredients values(551,'yellow onion cut into 1 double inch strips');
insert into ingredients values(552,'red or green bell pepper, cut into 2 double inch strips');
insert into ingredients values(553,'garlic cloves, minced');
insert into ingredients values(554,'small eggplant or about 2 1/2 cups, cut into 2 inch strips');
insert into ingredients values(555,'small jalapeno, diced');
insert into ingredients values(556,'of whole peeled tomatoes');
insert into ingredients values(557,'tomato paste');
insert into ingredients values(558,'paprika');
insert into ingredients values(559,'cumin');
insert into ingredients values(560,'salt & fresh ground black pepper');
insert into ingredients values(561,'eggs');
insert into ingredients values(562,'Italian flat leaf parsley, chopped for garnish');
insert into ingredients values(563,'Crusty bread or pita if desired');

insert into ingredients values(564,'Cottage Cheese Cut into bite sizes pieces, Paneer');
insert into ingredients values(565,'Plain Yogurt , Make sure the yogurt is thick');
insert into ingredients values(566,'Fresh Fenugreek Leaves , Chopped Fresh Methi');
insert into ingredients values(567,'Ginger plus Garlic Paste');
insert into ingredients values(568,'Oil ,Any flavorless oil');
insert into ingredients values(569,'water');
insert into ingredients values(570,'Large Onion, Finely Sliced');
insert into ingredients values(571,'Tomatoes, Finely Sliced');
insert into ingredients values(572,'Tomato Paste .If not available, can add tomato puree');
insert into ingredients values(573,'Large Green Chilies, Julienne, Add as per taste');
insert into ingredients values(574,'Orange Food Color');
insert into ingredients values(575,'Turmeric or Haldi');
insert into ingredients values(576,'Cinnamon Powder or Dalchini');
insert into ingredients values(577,'Garam Masala Powder, Homemade OR Store bought');
insert into ingredients values(578,'Coriander Powder OR Dhania');
insert into ingredients values(579,'Cumin Powder OR Jeera');
insert into ingredients values(580,'Powdered Red Chili Powder');
insert into ingredients values(581,'Powdered Salt ,As per your taste');

insert into ingredients values(582,'Red Onion');
insert into ingredients values(583,'Capsicum');
insert into ingredients values(584,'Carrots');
insert into ingredients values(585,'Beans');
insert into ingredients values(586,'Potato');
insert into ingredients values(587,'Peas');
insert into ingredients values(588,'Mint Leaves / Pudina Leaves');
insert into ingredients values(589,'Cinnamon Stick');
insert into ingredients values(590,'Marathi Moggu');
insert into ingredients values(591,'Sombhu / Fennel Seeds');
insert into ingredients values(592,'Kala Jeera');
insert into ingredients values(593,'Biryani Leaves');
insert into ingredients values(594,'Thick Coconut Milk');
insert into ingredients values(595,'Rice');
insert into ingredients values(596,'Salt');
insert into ingredients values(597,'Red Chilli Powder');
insert into ingredients values(598,'Coriander Powder');
insert into ingredients values(599,'Turmeric Powder');
insert into ingredients values(600,'Ghee or Butter');
insert into ingredients values(601,'Oil');
insert into ingredients values(602,'Tomato');
insert into ingredients values(603,'Pudina Leaves/Mint Leaves');
insert into ingredients values(604,'Ginger');
insert into ingredients values(605,'Coriander Leaves');

insert into ingredients values(606,'chicken stuffing mix');
insert into ingredients values(607,'cubed cooked chicken');
insert into ingredients values(608,'frozen broccoli florets, thawed');
insert into ingredients values(609,'condensed broccoli cheese soup, undiluted');
insert into ingredients values(610,'shredded cheddar cheese');

insert into ingredients values(611,'all-purpose flour');
insert into ingredients values(612,'baking soda');
insert into ingredients values(613,'salt');
insert into ingredients values(614,'vegetable shortening');
insert into ingredients values(615,'granulated sugar');
insert into ingredients values(616,'water');
insert into ingredients values(617,'semisweet chocolate morsels, divided 12 oz. pkg.');
insert into ingredients values(618,'large eggs');

insert into ingredients values(619,'recipe tart dough, made with half graham flour and half all-purpose flour');
insert into ingredients values(620,'eggs');
insert into ingredients values(621,'honey');
insert into ingredients values(622,'brown sugar');
insert into ingredients values(623,'melted butter');
insert into ingredients values(624,'rum');
insert into ingredients values(625,'dessicated coconut');
insert into ingredients values(626,'unsalted toasted cashews');
insert into ingredients values(627,'salt');
insert into ingredients values(628,'diced dried papaya and/or pineapple');

insert into ingredients values(629,'boneless skinless chicken breasts, cut into 1-inch chunks');
insert into ingredients values(630,'large eggs, beaten');
insert into ingredients values(631,'panko breadcrumbs');
insert into ingredients values(632,'honey');
insert into ingredients values(633,'soy sauce');
insert into ingredients values(634,'Sriracha sauce');
insert into ingredients values(635,'garlic powder');
insert into ingredients values(636,'warm water');
insert into ingredients values(637,'cornstarch');
insert into ingredients values(638,'green onions, thinly sliced');
insert into ingredients values(639,'sesame seeds');

insert into ingredients values(640,'sweet potato about 1 large, scrubbed, peeled and cut into 1 inch chunks');
insert into ingredients values(641,'vegan butter substitute, ghee, or salted butter');
insert into ingredients values(642,'cinnamon');
insert into ingredients values(643,'cumin');
insert into ingredients values(644,'salt');
insert into ingredients values(645,'chopped red onion');
insert into ingredients values(646,'chopped cilantro');
insert into ingredients values(647,'limes, 1 juiced and 1 cut in half');
insert into ingredients values(648,'white corn tortillas, warmed');
insert into ingredients values(649,'Olive oil');
insert into ingredients values(650,'Avocado Dipping Sauce');
insert into ingredients values(651,'Chopped lettuce, halved cherry tomatoes, chopped cilantro, hot sauce I use Cholula, and lime wedges for servin');

insert into ingredients values(652,'small clove garlic');
insert into ingredients values(653,'salt');
insert into ingredients values(654,'limes');
insert into ingredients values(655,'kosher salt');
insert into ingredients values(656,'chili powder');
insert into ingredients values(657,'extra-virgin olive oil');

insert into ingredients values(658,'sesame seeds');
insert into ingredients values(659,'poppy seeds');
insert into ingredients values(660,'white sugar');
insert into ingredients values(661,'olive oil');
insert into ingredients values(662,'distilled white vinegar');
insert into ingredients values(663,'paprika');
insert into ingredients values(664,'Worcestershire sauce');
insert into ingredients values(665,'minced onion');
insert into ingredients values(666,'fresh spinach - rinsed, dried and torn into bite-size pieces');
insert into ingredients values(667,'strawberries - cleaned, hulled and sliced');
insert into ingredients values(668,'almonds, blanched and slivered');